"""empty message

Revision ID: 47db6850d1e6
Revises: 4e726b9449ce
Create Date: 2026-02-06 23:31:11.082463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47db6850d1e6'
down_revision = '4e726b9449ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
