"""create users table

Revision ID: 775a15688689
Revises: c31fec25b1f5
Create Date: 2026-02-07 00:30:29.158454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775a15688689'
down_revision = 'c31fec25b1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
