"""create user model

Revision ID: 854f722712f2
Revises: e331355e68cb
Create Date: 2026-02-06 18:46:28.420144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854f722712f2'
down_revision = 'e331355e68cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
